### PR TITLE
Add Java automation

### PR DESCRIPTION
**Pull request by marcwrobel**
Fetch Java versions with their dates from https://www.java.com/releases/.

This script is using a new dependency: `requests-html` (https://requests-html.kennethreitz.org/). This is because https://www.java.com/releases/ needs JavaScript to render correctly. And for this to work `requests-html` automatically downloads Chromium.

Chromium is downloaded into `PYPPETEER_HOME`, that's why it was declared in the workflow. Note that declaring the same environment variable from the python script does not work.

### CODE REVIEW

**Comment by captn3m0** [comment]
I wrote down the bash-equivalent checking through the JSON requests made by the website. Takes a total of 3 requests:
1. Get the cache-id.
2. Get the content ID for the releases page.
3. Get the HTML for the given content-id.

```bash
USER_AGENT='Mozilla/5.0 Gecko/9 Firefox/999'
CACHE_ID=$(curl --silent 'https://www.java.com/releases/' --user-agent "$USER_AGENT" | \
awk -F\'  "/site: '_cache_(\w{4})/ {print \$2}")
RELEASE_PAGE_ID=282
# If needed, we can refresh this:
# RELEASE_PAGE_ID=$(curl --user-agent "$USER_AGENT" "https://www.java.com/$CACHE_ID/structure.json" | \
# jq '.base.pages[]|select(.pageUrl=="releases/fullmatrix/")|.id')

# Current value for the content-id is COREAC5B5E7D53E44A408D85E63A1C43FDF8, but might change?
CONTENT_ID=$(curl --silent --user-agent "$USER_AGENT" "https://www.java.com/$CACHE_ID/pages/$RELEASE_PAGE_ID.json" | \
  jq '.base.componentInstances | to_entries | .[] |select(.value.data.componentName | strings | test("Releases")) | \.value.data.contentIds[0]' -r)

# Can be refreshed if needed:
# CHANNEL_TOKEN=$(curl --silent --user-agent "$USER_AGENT" "https://www.java.com/$CACHE_ID/structure.json" | \
# jq '.siteInfo.base.properties.channelAccessTokens[0].value')

CHANNEL_TOKEN=1f7d2611846d4457b213dfc9048724dc
curl --silent --user-agent "$USER_AGENT" --url-query \
  "channelToken=$CHANNEL_TOKEN" \
  --url-query "q=(id eq \"$CONTENT_ID\")" \
  "https://www.java.com/content/published/api/v1.1/items" | \
  jq -r .items[0].fields.body > /tmp/java-releases.html
```

I don't expect the page ID to change (It has been `280` since the page was created in 2021). The only piece required is the content-id, which might not change over time (hard to validate, since it's not on web archive, and older caches return errors). Tried to rewrite this in Python, but the website seems to block anything but http/2.

**Comment by marcwrobel** [comment]
@captn3m0, what's wrong with the version I wrote ?

It seems to me it's a lot simpler to understand and does not require any refresh from time to time.

**Comment by marcwrobel** [comment]
The CI fails, but not because of the script. It fails on the auto-commit step `Aborting commit due to empty commit message.`. I don't understand why though.

**Comment by captn3m0** [comment]
Nothing wrong, I just like to code-golf website automation and avoid loading browsers. I'm unsure why this is breaking the CI. I ran the ruby script, and it's generating a correct commit message, same as it does for other PRs. 

Could you drop the JSON file from your commit, and force-push as a workaround?

**Comment by marcwrobel** [comment]
I did that, but it's not working either.

I think found the issue : in the GitHub CI logs we can see :

```
INPUT_COMMIT_AUTHOR: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
[add-java-automation 71f3bb0] 🤖: Automatic Update
 Author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
 325 files changed, 308109 insertions(+)
 create mode 100644 releases/java.json
 create mode 100644 ~/.cache/pyppeteer/local-chromium/588429/chrome-linux/MEIPreload/manifest.json
 create mode 100644 ~/.cache/pyppeteer/local-chromium/588429/chrome-linux/MEIPreload/preloaded_data.pb
 create mode 100755 ~/.cache/pyppeteer/local-chromium/588429/chrome-linux/chrome
 create mode 100644 ~/.cache/pyppeteer/local-chromium/588429/chrome-linux/chrome-wrapper
 ...
```

I think this means `pyppeteer`  has been created in a `~` directory inside the repository, not in `$HOME/.cache` like intended. Fixing that should fix the issue.

**Comment by marcwrobel** [comment]
Fixed.

I had to use directly `/home/runner` because using `~` does not work, despite what's explained in the https://github.com/actions/upload-artifact/tree/v2-preview#environment-variables-and-tilde-expansion. It's also not possible to use `$HOME`.

**Comment by captn3m0** [comment]
I was guessing if there were other files in the working directory, but didn't look like there should be from the code itself.

**Review by captn3m0 — APPROVED** [review]

**Comment by captn3m0** [comment]
`latest.py` might need some changes to pick-up new releases in some cases (6uXX for eg).

**Comment by marcwrobel** [comment]
I wonder if we should transform those release to `x.y.z` (such as 6u60 -> 6.0.80), like they did in https://github.com/foojayio/discoapi.

Too bad this API does not expose release dates (https://github.com/foojayio/discoapi/issues/67) !

**Pull request merged**
