### PR TITLE
[splunk] add automation

### PR DESCRIPTION
**Pull request by dadav**
This automation fetches the version from the [docs](https://docs.splunk.com/Documentation/Splunk/7.3.5/ReleaseNotes/MeetSplunk#What.27s_New_in_7.3.5). The release information only seems to be available from 7.2 on.

The automation checks for the format

`Splunk Enterprise 7.3.5.2 was released on May 26, 2020.` 

with a regex. The versions are 

`major.minor.patch`

and sometimes major.minor.patch.**anothernumber**. I don't know why they do this and I couldn't find an explanation. I've kept these versions in, but I'm unsure if this gets handled correctly by **endoflife.date**.

### CODE REVIEW

**Comment by marcwrobel** [comment]
Hi @dadav, thanks for this contribution. I will have a look at it asap this week.

> and sometimes major.minor.patch.**anothernumber**. I don't know why they do this and I couldn't find an explanation. I've kept these versions in, but I'm unsure if this gets handled correctly by **endoflife.date**.

It should work, it's not the only product that is using a 'tiny' version number. For example Openshift [is using it too](https://github.com/endoflife-date/release-data/commit/27e94d3078a32f2e0545e5b005828782d5e2f878).

**Comment by marcwrobel** [comment]
@dadav, I refactored it to something more concise and readable (IMO, I am not very fluent in Python and does not know the idioms). Hope you are ok with this (note: I just found I should have been called the options values `minor_release`, as it is in fact the patch version).

This refactored script also prints versions as they are found. Thanks to that I found out that most of the pages are downloaded for nothing. For instance pages 7.2.0 to 7.2.10 are downloaded but the result would be the same if only the 7.2.10 page were downloaded. This is an issue because the page are quite long to load, so we must find a way to only get the page for the last version of an x.y cycle.

Another issue: x.y.0 versions dates are never found. This is an issue because our automation will take the x.y.1 as x.y release date. So we must also parse sentences like `Splunk Enterprise 9.0 was released on June 14, 2022.`.

**Comment by dadav** [comment]
@marcwrobel Ok, I will have a look at these points. I knew that many pages are empty, that's why I sorted the versions before fetching the pages and checked if the versions date was already found. I also thought about using some parallelism library (aiohttp) to speed things up, but this seems more like a throw-resources-at-the-problem kind of solution.

**Comment by dadav** [comment]
Before fix: 66 fetches needed. Time: 3:34 mins

**Comment by dadav** [comment]
After fix: 17 fetches needed. Time: 25s

**Comment by dadav** [comment]
13 fetches, 20s

**Comment by dadav** [comment]
And thats it....I think I can't get a better result ^^

**Comment by marcwrobel** [comment]
Thanks again @dadav !

**Pull request merged**
