### PR TITLE
[macOS] Accept all kind of spaces in regexes (fixes #47)

### LINKED ISSUE #47: macOS 13.1 missing
Hi!

I'm using the macos.json as input for one of my automations and i notice that macOS 13.1 (22C65), released 2022-12-13, is missing from the release data. How can i help? Can i? Should i? Is the data file automatically updated (and is now stuck) or manually curated?

 ~rL

### PR DESCRIPTION
**Pull request by marcwrobel**
There were two issues with the macOS regexes:

- The regexex accepted only spaces separator. But non-breakable spaces are also used from time to time. Replacing spaces by \s fixed the issue (other product regexes were also updated - never know).
- The first regex, the one that accepted major releases with no minor version, were not useful (covered by the second regex) and partly catched valid versions (such as 13.1), who was then ignored. I removed it.

### CODE REVIEW

**Comment by marcwrobel** [comment]
@captn3m0, I did not find 10, 11, 12 versions on the parsed pages, so I think their removal is OK. The `Sierra and beyond` regex is working though because it is correctly matching against the version `13`.

**Comment by marcwrobel** [comment]
> Give me a few hours. I remember explicitly fixing the .0 versions somehow, want to double check that before merging.

OK. I had the impression, for the 11/12 versions that they were called 11.0/12.0 on the Apple page. But you may have done that for the macOS 10 version, which disappeared. Something must be done for that before merging the PR.

**Comment by marcwrobel** [comment]
> But you may have done that for the macOS 10 version, which disappeared. Something must be done for that before merging the PR.

Think it's OK : there is still macOS 10.12 (released on 2016-09-20) and macOS 10 is not a release cycle (on https://endoflife.date/macos).

**Review by captn3m0 — APPROVED** [review]

**Comment by captn3m0** [comment]
Looked into it, the dates match the `x.0.1` release because the `x.0` announcements are marked as Preinstalled.

**Pull request merged**
