### PR TITLE
Add docker_hub method

### PR DESCRIPTION
**Pull request by marcwrobel**
Will replace Ruby-implemented dockerhub method (only used by Amazon Linux at the moment.

### CODE REVIEW

**Comment by marcwrobel** [comment]
To test, use the following auto configuration in amazon-linux.md:

```yaml
auto:
-   docker_hub: library/amazonlinux
    # TODO: Fix this regex to exclude RC releases
    regex: ^(?:\d+(\.\d+){2,4})$
```

**Comment by captn3m0** [comment]
Drop the ruby parts as well here?

**Comment by marcwrobel** [comment]
Not yet, I would like to test it before.

**Review by marcwrobel — COMMENTED** [review]
No change, LGTM. Merging.

**Comment by usta** [comment]
@marcwrobel @captn3m0 looks nice , but i would be more happy if we can keep our writing style ( i mean camelCase )
 `dockerHub` instead of using `docker_hub` . Is this too late to implement ?

**Pull request merged**
