### PR TITLE
Add macOS Ventura 13.0 release date

### PR DESCRIPTION
**Pull request by nobelharvards**
macOS Ventura 13.0 was released on the 24th of October, 2022.

### CODE REVIEW

**Comment by hugovk** [comment]
New releases cycles are not (yet) automatically added, but once added should be auto-updated.

**Review by hugovk — APPROVED** [review]
Confirmed release date:

* https://en.wikipedia.org/wiki/MacOS_Ventura#Release_history
* https://support.apple.com/en-gb/HT213488

Thanks!

**Comment by captn3m0** [comment]
Thanks for the update 💯

**Comment by captn3m0** [comment]
I didn't realise the PR was for this repo (was using GitHub Mobile). The data is re-generated every run, so 63cca8f016b71653ed04d10541e056bb5a43fb2c actually undid this PR.

The real issue is that the regex we use [in the apple.py script](https://github.com/endoflife-date/release-data/blob/main/src/apple.py) mandates dots in version numbers. I've fixed that in #30, so that should be sorted soon.

Note that, a deletion here will never remove data from <https://endoflife.date/macos> - our [automation](https://github.com/endoflife-date/endoflife.date/wiki/Automation#latest-update) only updates data if it finds matching data in this repo.

**Pull request merged**
