### PR TITLE
[typo3] Add release automation

### LINKED ISSUE #92: [typo3] Switch to API for retrieving the versions
ELTS versions are not tagged on https://github.com/TYPO3/typo3 (which is OK because those versions are only for typo3 customers). We should use [Typo3 API](https://get.typo3.org/api/doc) instead because it includes ELTS versions.

Source : https://github.com/endoflife-date/endoflife.date/pull/2884#issuecomment-1522804151.

### LINKED ISSUE #109: [rocky-linux] Improve automation
Distrowatch is lack version 8.8, which was released on May 30, 2023. We could use https://wiki.rockylinux.org/rocky/version/ instead.

### PR DESCRIPTION
**Pull request by captn3m0**
Using tags misses all ELTS releases, which are relevant for ELTS-only
release cycles.

Fixes #92

Important changes:

- very old v3 and v4 releases completely dropped except for 3.3.0, and 3.5.0.
  We track only as far back as v7, so dropping v4 and earlier
  should be fine.
- 9.3.2 is missing.
- 7.0.1 is missing.

Both of the above are superseded, so it should be okay.

**Complete Diff**

```diff
--- a/releases/typo3.json
+++ b/releases/typo3.json
@@ -39,0 +40,2 @@
+json["10.4.38"] = "2023-07-04";
+json["10.4.39"] = "2023-07-25";
@@ -40,0 +43 @@
+json["10.4.40"] = "2023-07-25";
@@ -99,2 +102,2 @@
-json["3.6.0"] = "2004-04-30";
-json["3.6.1"] = "2004-05-11";
+json["3.3.0"] = "2002-06-03";
+json["3.5.0"] = "2003-02-18";
@@ -102,8 +105,2 @@
-json["3.7.0"] = "2004-09-24";
-json["3.7.1"] = "2005-05-21";
-json["3.8.0"] = "2005-05-22";
-json["4.0.0"] = "2006-04-07";
-json["4.0.1"] = "2006-08-01";
-json["4.0.10"] = "2009-01-20";
-json["4.0.11"] = "2009-01-24";
-json["4.0.12"] = "2009-02-10";
+json["3.7.1"] = "2005-05-23";
+json["3.8.1"] = "2005-11-14";
@@ -111,12 +107,0 @@
-json["4.0.2"] = "2006-09-24";
-json["4.0.3"] = "2006-12-11";
-json["4.0.4"] = "2007-01-11";
-json["4.0.5"] = "2007-02-21";
-json["4.0.6"] = "2007-04-02";
-json["4.0.7"] = "2007-07-16";
-json["4.0.8"] = "2007-12-10";
-json["4.0.9"] = "2008-06-11";
-json["4.1.0"] = "2007-03-06";
-json["4.1.1"] = "2007-04-02";
-json["4.1.10"] = "2009-02-10";
-json["4.1.11"] = "2009-07-02";
@@ -127,10 +111,0 @@
-json["4.1.2"] = "2007-07-16";
-json["4.1.3"] = "2007-10-22";
-json["4.1.4"] = "2007-12-10";
-json["4.1.5"] = "2007-12-14";
-json["4.1.6"] = "2008-03-03";
-json["4.1.7"] = "2008-06-11";
-json["4.1.8"] = "2009-01-20";
-json["4.1.9"] = "2009-01-24";
-json["4.2.0"] = "2008-05-24";
-json["4.2.1"] = "2008-06-11";
@@ -145,6 +119,0 @@
-json["4.2.2"] = "2008-10-06";
-json["4.2.3"] = "2008-11-11";
-json["4.2.4"] = "2009-01-20";
-json["4.2.5"] = "2009-01-24";
-json["4.2.6"] = "2009-02-10";
-json["4.2.7"] = "2009-07-02";
@@ -184 +153 @@
-json["4.5.0"] = "2011-01-26";
+json["4.5.0"] = "2011-02-02";
@@ -318,0 +288,8 @@
+json["6.2.32"] = "2017-08-29";
+json["6.2.33"] = "2017-08-30";
+json["6.2.34"] = "2017-09-05";
+json["6.2.35"] = "2017-09-06";
+json["6.2.36"] = "2018-03-13";
+json["6.2.37"] = "2018-05-22";
+json["6.2.38"] = "2018-07-12";
+json["6.2.39"] = "2018-12-11";
@@ -319,0 +297,10 @@
+json["6.2.40"] = "2019-01-22";
+json["6.2.41"] = "2019-03-19";
+json["6.2.42"] = "2019-05-07";
+json["6.2.43"] = "2019-05-08";
+json["6.2.44"] = "2019-06-25";
+json["6.2.45"] = "2019-07-02";
+json["6.2.46"] = "2019-08-20";
+json["6.2.47"] = "2019-12-17";
+json["6.2.48"] = "2020-01-28";
+json["6.2.49"] = "2020-05-12";
@@ -320,0 +308,8 @@
+json["6.2.50"] = "2020-05-19";
+json["6.2.51"] = "2020-07-07";
+json["6.2.52"] = "2020-07-28";
+json["6.2.53"] = "2020-09-08";
+json["6.2.54"] = "2020-11-17";
+json["6.2.55"] = "2020-11-17";
+json["6.2.56"] = "2020-12-18";
+json["6.2.57"] = "2021-03-16";
@@ -326 +320,0 @@
-json["7.0.1"] = "2014-12-10";
@@ -360,0 +355,7 @@
+json["7.6.33"] = "2019-01-22";
+json["7.6.34"] = "2019-01-23";
+json["7.6.35"] = "2019-03-21";
+json["7.6.36"] = "2019-05-07";
+json["7.6.37"] = "2019-05-08";
+json["7.6.38"] = "2019-06-25";
+json["7.6.39"] = "2019-08-20";
@@ -361,0 +363,10 @@
+json["7.6.40"] = "2019-12-17";
+json["7.6.41"] = "2020-01-28";
+json["7.6.42"] = "2020-05-12";
+json["7.6.43"] = "2020-05-19";
+json["7.6.44"] = "2020-07-07";
+json["7.6.45"] = "2020-07-07";
+json["7.6.46"] = "2020-07-28";
+json["7.6.47"] = "2020-09-08";
+json["7.6.48"] = "2020-11-17";
+json["7.6.49"] = "2020-11-17";
@@ -362,0 +374,9 @@
+json["7.6.50"] = "2020-12-18";
+json["7.6.51"] = "2021-03-16";
+json["7.6.52"] = "2021-07-20";
+json["7.6.53"] = "2021-08-10";
+json["7.6.54"] = "2021-08-16";
+json["7.6.55"] = "2021-11-11";
+json["7.6.56"] = "2022-02-22";
+json["7.6.57"] = "2022-06-14";
+json["7.6.58"] = "2022-09-12";
@@ -407 +427 @@
-json["8.7.31"] = "2020-02-18";
+json["8.7.31"] = "2020-02-17";
@@ -408,0 +429,7 @@
+json["8.7.33"] = "2020-05-12";
+json["8.7.34"] = "2020-05-19";
+json["8.7.35"] = "2020-07-07";
+json["8.7.36"] = "2020-07-28";
+json["8.7.37"] = "2020-09-08";
+json["8.7.38"] = "2020-11-17";
+json["8.7.39"] = "2020-12-18";
@@ -409,0 +437,10 @@
+json["8.7.40"] = "2021-03-16";
+json["8.7.41"] = "2021-07-20";
+json["8.7.42"] = "2021-08-10";
+json["8.7.43"] = "2021-08-16";
+json["8.7.44"] = "2021-11-11";
+json["8.7.45"] = "2022-02-22";
+json["8.7.46"] = "2022-04-12";
+json["8.7.47"] = "2022-06-14";
+json["8.7.48"] = "2022-09-12";
+json["8.7.49"] = "2022-12-13";
@@ -410,0 +448,5 @@
+json["8.7.50"] = "2022-12-15";
+json["8.7.51"] = "2023-02-07";
+json["8.7.52"] = "2023-07-04";
+json["8.7.53"] = "2023-07-25";
+json["8.7.54"] = "2023-07-25";
@@ -421 +462,0 @@
-json["9.3.2"] = "2018-07-12";
@@ -430 +471 @@
-json["9.5.14"] = "2020-02-18";
+json["9.5.14"] = "2020-02-17";
@@ -449,0 +491,8 @@
+json["9.5.32"] = "2021-11-11";
+json["9.5.33"] = "2022-02-22";
+json["9.5.34"] = "2022-04-12";
+json["9.5.35"] = "2022-06-14";
+json["9.5.36"] = "2022-06-15";
+json["9.5.37"] = "2022-09-12";
+json["9.5.38"] = "2022-12-13";
+json["9.5.39"] = "2022-12-15";
@@ -450,0 +500,4 @@
+json["9.5.40"] = "2023-02-07";
+json["9.5.41"] = "2023-07-04";
+json["9.5.42"] = "2023-07-25";
+json["9.5.43"] = "2023-07-25";
```

### CODE REVIEW

**Comment by marcwrobel** [comment]
That's odd, there is an auto commit in this PR (https://github.com/endoflife-date/release-data/pull/142/commits/60a13d92bf77a26ba457a80e3013c166d3cf0748), but it does not show up in the diff (https://github.com/endoflife-date/release-data/pull/142/files). Will have a look tomorrow.

**Comment by captn3m0** [comment]
I committed the new typo3.json, and the auto commit in this PR is using the git automation, so it "resets" typo3.json to the same state as in `main`. Hence doesn't show up in the diff.

What I need to check is how the custom typo3.py automation is getting overridden.

**Comment by marcwrobel** [comment]
> I committed the new typo3.json, and the auto commit in this PR is using the git automation, so it "resets" typo3.json to the same state as in `main`. Hence doesn't show up in the diff.

Ok, did not thought about it.

> What I need to check is how the custom typo3.py automation is getting overridden.

Why not just creating the endoflife.date PR with the same branch name so automation would work "as usual" ?

**Review by marcwrobel — APPROVED** [review]
Verified the expected diff, LGTM.

I let you create the corresponding endoflife.date PR and clean up the commits/merge.

**Review by marcwrobel — APPROVED** [review]
Refactored the script a bit and rechecked with https://jsondiff.com/, LGTM. Merging.

**Pull request merged**
